/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentStudentIdRouteImport } from './routes/student.$studentId'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated.chat.index'
import { Route as AuthenticatedMeTakeTestRouteImport } from './routes/_authenticated.me.take-test'
import { Route as AuthenticatedMeSimulatorRouteImport } from './routes/_authenticated.me.simulator'
import { Route as AuthenticatedMeRoadmapRouteImport } from './routes/_authenticated.me.roadmap'
import { Route as AuthenticatedMeProgressRouteImport } from './routes/_authenticated.me.progress'
import { Route as AuthenticatedMeMockTestsRouteImport } from './routes/_authenticated.me.mock-tests'
import { Route as AuthenticatedMeLearnerRouteImport } from './routes/_authenticated.me.learner'
import { Route as AuthenticatedMeExamStrategyRouteImport } from './routes/_authenticated.me.exam-strategy'
import { Route as AuthenticatedMeCurriculumRouteImport } from './routes/_authenticated.me.curriculum'
import { Route as AuthenticatedMeCriticRouteImport } from './routes/_authenticated.me.critic'
import { Route as AuthenticatedMeCounterfactualRouteImport } from './routes/_authenticated.me.counterfactual'
import { Route as AuthenticatedMeArchitectureRouteImport } from './routes/_authenticated.me.architecture'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated.chat.$threadId'
import { Route as StudentStudentIdChatThreadIdRouteImport } from './routes/student.$studentId.chat.$threadId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStudentIdRoute = StudentStudentIdRouteImport.update({
  id: '/student/$studentId',
  path: '/student/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeTakeTestRoute = AuthenticatedMeTakeTestRouteImport.update({
  id: '/me/take-test',
  path: '/me/take-test',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeSimulatorRoute =
  AuthenticatedMeSimulatorRouteImport.update({
    id: '/me/simulator',
    path: '/me/simulator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeRoadmapRoute = AuthenticatedMeRoadmapRouteImport.update({
  id: '/me/roadmap',
  path: '/me/roadmap',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeProgressRoute = AuthenticatedMeProgressRouteImport.update({
  id: '/me/progress',
  path: '/me/progress',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeMockTestsRoute =
  AuthenticatedMeMockTestsRouteImport.update({
    id: '/me/mock-tests',
    path: '/me/mock-tests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeLearnerRoute = AuthenticatedMeLearnerRouteImport.update({
  id: '/me/learner',
  path: '/me/learner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeExamStrategyRoute =
  AuthenticatedMeExamStrategyRouteImport.update({
    id: '/me/exam-strategy',
    path: '/me/exam-strategy',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeCurriculumRoute =
  AuthenticatedMeCurriculumRouteImport.update({
    id: '/me/curriculum',
    path: '/me/curriculum',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeCriticRoute = AuthenticatedMeCriticRouteImport.update({
  id: '/me/critic',
  path: '/me/critic',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeCounterfactualRoute =
  AuthenticatedMeCounterfactualRouteImport.update({
    id: '/me/counterfactual',
    path: '/me/counterfactual',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeArchitectureRoute =
  AuthenticatedMeArchitectureRouteImport.update({
    id: '/me/architecture',
    path: '/me/architecture',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const StudentStudentIdChatThreadIdRoute =
  StudentStudentIdChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => StudentStudentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/student/$studentId': typeof StudentStudentIdRouteWithChildren
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/me/architecture': typeof AuthenticatedMeArchitectureRoute
  '/me/counterfactual': typeof AuthenticatedMeCounterfactualRoute
  '/me/critic': typeof AuthenticatedMeCriticRoute
  '/me/curriculum': typeof AuthenticatedMeCurriculumRoute
  '/me/exam-strategy': typeof AuthenticatedMeExamStrategyRoute
  '/me/learner': typeof AuthenticatedMeLearnerRoute
  '/me/mock-tests': typeof AuthenticatedMeMockTestsRoute
  '/me/progress': typeof AuthenticatedMeProgressRoute
  '/me/roadmap': typeof AuthenticatedMeRoadmapRoute
  '/me/simulator': typeof AuthenticatedMeSimulatorRoute
  '/me/take-test': typeof AuthenticatedMeTakeTestRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/student/$studentId/chat/$threadId': typeof StudentStudentIdChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/student/$studentId': typeof StudentStudentIdRouteWithChildren
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/me/architecture': typeof AuthenticatedMeArchitectureRoute
  '/me/counterfactual': typeof AuthenticatedMeCounterfactualRoute
  '/me/critic': typeof AuthenticatedMeCriticRoute
  '/me/curriculum': typeof AuthenticatedMeCurriculumRoute
  '/me/exam-strategy': typeof AuthenticatedMeExamStrategyRoute
  '/me/learner': typeof AuthenticatedMeLearnerRoute
  '/me/mock-tests': typeof AuthenticatedMeMockTestsRoute
  '/me/progress': typeof AuthenticatedMeProgressRoute
  '/me/roadmap': typeof AuthenticatedMeRoadmapRoute
  '/me/simulator': typeof AuthenticatedMeSimulatorRoute
  '/me/take-test': typeof AuthenticatedMeTakeTestRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/student/$studentId/chat/$threadId': typeof StudentStudentIdChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/student/$studentId': typeof StudentStudentIdRouteWithChildren
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/me/architecture': typeof AuthenticatedMeArchitectureRoute
  '/_authenticated/me/counterfactual': typeof AuthenticatedMeCounterfactualRoute
  '/_authenticated/me/critic': typeof AuthenticatedMeCriticRoute
  '/_authenticated/me/curriculum': typeof AuthenticatedMeCurriculumRoute
  '/_authenticated/me/exam-strategy': typeof AuthenticatedMeExamStrategyRoute
  '/_authenticated/me/learner': typeof AuthenticatedMeLearnerRoute
  '/_authenticated/me/mock-tests': typeof AuthenticatedMeMockTestsRoute
  '/_authenticated/me/progress': typeof AuthenticatedMeProgressRoute
  '/_authenticated/me/roadmap': typeof AuthenticatedMeRoadmapRoute
  '/_authenticated/me/simulator': typeof AuthenticatedMeSimulatorRoute
  '/_authenticated/me/take-test': typeof AuthenticatedMeTakeTestRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/student/$studentId/chat/$threadId': typeof StudentStudentIdChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/api/chat'
    | '/api/health'
    | '/student/$studentId'
    | '/chat/$threadId'
    | '/me/architecture'
    | '/me/counterfactual'
    | '/me/critic'
    | '/me/curriculum'
    | '/me/exam-strategy'
    | '/me/learner'
    | '/me/mock-tests'
    | '/me/progress'
    | '/me/roadmap'
    | '/me/simulator'
    | '/me/take-test'
    | '/chat/'
    | '/student/$studentId/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/api/chat'
    | '/api/health'
    | '/student/$studentId'
    | '/chat/$threadId'
    | '/me/architecture'
    | '/me/counterfactual'
    | '/me/critic'
    | '/me/curriculum'
    | '/me/exam-strategy'
    | '/me/learner'
    | '/me/mock-tests'
    | '/me/progress'
    | '/me/roadmap'
    | '/me/simulator'
    | '/me/take-test'
    | '/chat'
    | '/student/$studentId/chat/$threadId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/api/chat'
    | '/api/health'
    | '/student/$studentId'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/me/architecture'
    | '/_authenticated/me/counterfactual'
    | '/_authenticated/me/critic'
    | '/_authenticated/me/curriculum'
    | '/_authenticated/me/exam-strategy'
    | '/_authenticated/me/learner'
    | '/_authenticated/me/mock-tests'
    | '/_authenticated/me/progress'
    | '/_authenticated/me/roadmap'
    | '/_authenticated/me/simulator'
    | '/_authenticated/me/take-test'
    | '/_authenticated/chat/'
    | '/student/$studentId/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  StudentStudentIdRoute: typeof StudentStudentIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/$studentId': {
      id: '/student/$studentId'
      path: '/student/$studentId'
      fullPath: '/student/$studentId'
      preLoaderRoute: typeof StudentStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/take-test': {
      id: '/_authenticated/me/take-test'
      path: '/me/take-test'
      fullPath: '/me/take-test'
      preLoaderRoute: typeof AuthenticatedMeTakeTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/simulator': {
      id: '/_authenticated/me/simulator'
      path: '/me/simulator'
      fullPath: '/me/simulator'
      preLoaderRoute: typeof AuthenticatedMeSimulatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/roadmap': {
      id: '/_authenticated/me/roadmap'
      path: '/me/roadmap'
      fullPath: '/me/roadmap'
      preLoaderRoute: typeof AuthenticatedMeRoadmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/progress': {
      id: '/_authenticated/me/progress'
      path: '/me/progress'
      fullPath: '/me/progress'
      preLoaderRoute: typeof AuthenticatedMeProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/mock-tests': {
      id: '/_authenticated/me/mock-tests'
      path: '/me/mock-tests'
      fullPath: '/me/mock-tests'
      preLoaderRoute: typeof AuthenticatedMeMockTestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/learner': {
      id: '/_authenticated/me/learner'
      path: '/me/learner'
      fullPath: '/me/learner'
      preLoaderRoute: typeof AuthenticatedMeLearnerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/exam-strategy': {
      id: '/_authenticated/me/exam-strategy'
      path: '/me/exam-strategy'
      fullPath: '/me/exam-strategy'
      preLoaderRoute: typeof AuthenticatedMeExamStrategyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/curriculum': {
      id: '/_authenticated/me/curriculum'
      path: '/me/curriculum'
      fullPath: '/me/curriculum'
      preLoaderRoute: typeof AuthenticatedMeCurriculumRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/critic': {
      id: '/_authenticated/me/critic'
      path: '/me/critic'
      fullPath: '/me/critic'
      preLoaderRoute: typeof AuthenticatedMeCriticRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/counterfactual': {
      id: '/_authenticated/me/counterfactual'
      path: '/me/counterfactual'
      fullPath: '/me/counterfactual'
      preLoaderRoute: typeof AuthenticatedMeCounterfactualRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/architecture': {
      id: '/_authenticated/me/architecture'
      path: '/me/architecture'
      fullPath: '/me/architecture'
      preLoaderRoute: typeof AuthenticatedMeArchitectureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/student/$studentId/chat/$threadId': {
      id: '/student/$studentId/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/student/$studentId/chat/$threadId'
      preLoaderRoute: typeof StudentStudentIdChatThreadIdRouteImport
      parentRoute: typeof StudentStudentIdRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedMeArchitectureRoute: typeof AuthenticatedMeArchitectureRoute
  AuthenticatedMeCounterfactualRoute: typeof AuthenticatedMeCounterfactualRoute
  AuthenticatedMeCriticRoute: typeof AuthenticatedMeCriticRoute
  AuthenticatedMeCurriculumRoute: typeof AuthenticatedMeCurriculumRoute
  AuthenticatedMeExamStrategyRoute: typeof AuthenticatedMeExamStrategyRoute
  AuthenticatedMeLearnerRoute: typeof AuthenticatedMeLearnerRoute
  AuthenticatedMeMockTestsRoute: typeof AuthenticatedMeMockTestsRoute
  AuthenticatedMeProgressRoute: typeof AuthenticatedMeProgressRoute
  AuthenticatedMeRoadmapRoute: typeof AuthenticatedMeRoadmapRoute
  AuthenticatedMeSimulatorRoute: typeof AuthenticatedMeSimulatorRoute
  AuthenticatedMeTakeTestRoute: typeof AuthenticatedMeTakeTestRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedMeArchitectureRoute: AuthenticatedMeArchitectureRoute,
  AuthenticatedMeCounterfactualRoute: AuthenticatedMeCounterfactualRoute,
  AuthenticatedMeCriticRoute: AuthenticatedMeCriticRoute,
  AuthenticatedMeCurriculumRoute: AuthenticatedMeCurriculumRoute,
  AuthenticatedMeExamStrategyRoute: AuthenticatedMeExamStrategyRoute,
  AuthenticatedMeLearnerRoute: AuthenticatedMeLearnerRoute,
  AuthenticatedMeMockTestsRoute: AuthenticatedMeMockTestsRoute,
  AuthenticatedMeProgressRoute: AuthenticatedMeProgressRoute,
  AuthenticatedMeRoadmapRoute: AuthenticatedMeRoadmapRoute,
  AuthenticatedMeSimulatorRoute: AuthenticatedMeSimulatorRoute,
  AuthenticatedMeTakeTestRoute: AuthenticatedMeTakeTestRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface StudentStudentIdRouteChildren {
  StudentStudentIdChatThreadIdRoute: typeof StudentStudentIdChatThreadIdRoute
}

const StudentStudentIdRouteChildren: StudentStudentIdRouteChildren = {
  StudentStudentIdChatThreadIdRoute: StudentStudentIdChatThreadIdRoute,
}

const StudentStudentIdRouteWithChildren =
  StudentStudentIdRoute._addFileChildren(StudentStudentIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  StudentStudentIdRoute: StudentStudentIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
